User Agent: 'Moderation bot made with love by /u/CrackpotXAN4'
Username: 'FightPorn'
Password: 'FightP0rnOnReddit!'
Client ID: '1GL8sFHQ-vVG-Q'
Client Secret: '0ZVvRo3sKvKco7bPPVpN5E9w_w'
Subreddits:
    - 'FightPorn'
